# Generated by Django 4.2.5 on 2023-10-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("abdm_hiu", "0001_consentrequest_and_consentartefact"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthInformationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_request_id", models.UUIDField(unique=True)),
                ("transaction_id", models.UUIDField(null=True, unique=True)),
                ("key_material", models.JSONField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending request from Gateway"),
                            ("REQUESTED", "Requested"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ERROR", "Error occurred"),
                            ("TRANSFERRED", "Transferred"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                ("error", models.JSONField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "consent_artefact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_information_request",
                        to="abdm_hiu.consentartefact",
                        to_field="artefact_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthDataReceipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.SmallIntegerField()),
                ("care_contexts", models.JSONField()),
                ("status", models.BooleanField(default=False)),
                ("error", models.TextField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "health_information_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_data_receipt",
                        to="abdm_hiu.healthinformationrequest",
                        to_field="transaction_id",
                    ),
                ),
            ],
        ),
    ]
