# Generated by Django 3.2.23 on 2024-03-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm_hiu', '0003_alter_consentartefact_consent_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrequest',
            name='date_denied',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='date_granted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='date_revoked',
            field=models.DateTimeField(null=True),
        ),
    ]
