# Generated by Django 4.2.5 on 2023-10-03 11:37

from abdm_integrator.settings import app_settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(app_settings.USER_MODEL),
        ("abdm_hip", "0001_consent_artefact"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_reference", models.CharField(max_length=255)),
                ("hip_id", models.CharField(max_length=255)),
                ("gateway_request_id", models.UUIDField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending request from Gateway"),
                            ("SUCCESS", "Success"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                ("error", models.JSONField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="link_requests",
                        to=app_settings.USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkCareContext",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("care_context_number", models.CharField(max_length=255)),
                ("health_info_types", models.JSONField(default=list)),
                (
                    "link_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_contexts",
                        to="abdm_hip.linkrequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="linkrequest",
            index=models.Index(
                fields=["patient_reference", "hip_id"],
                name="abdm_hip_li_patient_4b697b_idx",
            ),
        ),
    ]
